### ISSUE TITLE
MVP API 추가

### ISSUE THREAD

**Issue by kang-jae-heok** [f-lab-edu/purple-coin#2]
### Market
- [x] 전체 코인리스트 불러오기
- [x] 특정 코인 리스트 불러오기(관심 코인, 검색된 코인)
### DetailCoin
- [x] 해당 코인 상세 정보 가져오기
- [ ] 해당 코인 주문 리스트 데이터 추가
- [ ] 해당 코인 매도, 매수 주문

**Comment by abdul0986** [comment]
조금 상세한 설명이 있으면 좋을 것 같습니다. 이를태면 Main은 어떤 기능을 구현할 예정인지, Market의 핵심 구현 기능은 무엇인지 등등..
